# Generated by Django 5.0.3 on 2024-04-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkouthistory',
            name='checkout_condition',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkouthistory',
            name='return_condition',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
